# ==========================================================
# pdf_utils.py - Generate laporan hasil ujian (PDF) &
# sertifikat kelulusan (PDF)
# ==========================================================
from fpdf import FPDF
from fpdf.enums import XPos, YPos
from datetime import datetime


def _status_label(score):
    if score >= 80:
        return "LUAR BIASA!"
    elif score >= 70:
        return "BAGUS!"
    elif score >= 60:
        return "CUKUP"
    return "PERLU BELAJAR LAGI"


def _fmt_answer(ans):
    if isinstance(ans, list):
        return ", ".join(ans) if ans else "-"
    return ans if ans not in (None, "") else "-"


def create_pdf_report(name, sid, module, score, details, status="Selesai"):
    pdf = FPDF()
    pdf.add_page()

    pdf.set_font("helvetica", "B", 18)
    pdf.cell(0, 12, "LAPORAN HASIL BELAJAR", ln=True, align="C")

    pdf.ln(5)
    pdf.set_font("helvetica", "", 12)
    pdf.cell(0, 8, f"Nama: {name}", ln=True)
    pdf.cell(0, 8, f"ID Siswa: {sid}", ln=True)
    pdf.cell(0, 8, f"Modul: {module}", ln=True)
    pdf.cell(0, 8, f"Tanggal: {datetime.now().strftime('%d-%m-%Y %H:%M')}", ln=True)

    pdf.ln(5)
    pdf.set_font("helvetica", "B", 14)
    if status == "Menunggu Review":
        pdf.cell(0, 10, f"Nilai Sementara: {score}/100 (Menunggu Review Soal Essay)", ln=True)
    else:
        pdf.cell(0, 10, f"Nilai: {score}/100 - {_status_label(score)}", ln=True)

    pdf.ln(5)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 8, "DETAIL JAWABAN:", ln=True)

    for i, d in enumerate(details, 1):
        pdf.ln(3)
        pdf.set_font("helvetica", "B", 11)
        pdf.multi_cell(0, 7, f"Soal {i} [{d.get('type','single').upper()}]: {d['question']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        pdf.set_font("helvetica", "", 10)
        pdf.multi_cell(0, 6, f"Jawaban Anda: {_fmt_answer(d['user_answer'])}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

        if d.get("type") == "essay":
            if d.get("needs_review"):
                pdf.set_font("helvetica", "B", 10)
                pdf.set_text_color(200, 140, 0)
                pdf.cell(0, 6, "Status: MENUNGGU DINILAI GURU", ln=True)
                pdf.set_text_color(0, 0, 0)
            else:
                pdf.multi_cell(0, 6, f"Skor Essay: {d['score']}/100", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
        else:
            pdf.multi_cell(0, 6, f"Jawaban Benar: {_fmt_answer(d['correct_answer'])}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)
            pdf.set_font("helvetica", "B", 10)
            if d["is_correct"]:
                pdf.set_text_color(0, 150, 0)
                pdf.cell(0, 6, "Status: BENAR", ln=True)
            else:
                pdf.set_text_color(200, 0, 0)
                pdf.cell(0, 6, "Status: SALAH", ln=True)
            pdf.set_text_color(0, 0, 0)

        if d.get("explanation"):
            pdf.set_font("helvetica", "I", 9)
            pdf.multi_cell(0, 6, f"Penjelasan: {d['explanation']}", new_x=XPos.LMARGIN, new_y=YPos.NEXT)

    pdf.ln(10)
    pdf.set_font("helvetica", "I", 8)
    pdf.cell(0, 5, "Generated by Advanced Mini LMS | Keep Learning!", ln=True, align="C")

    return bytes(pdf.output())


def create_certificate(name, sid, module, score, passing_grade=60):
    """Sertifikat landscape sederhana untuk siswa yang lulus."""
    pdf = FPDF(orientation="L", unit="mm", format="A4")
    pdf.add_page()

    # Border dekoratif
    pdf.set_draw_color(102, 126, 234)
    pdf.set_line_width(1.5)
    pdf.rect(8, 8, 281, 181)
    pdf.set_line_width(0.5)
    pdf.rect(12, 12, 273, 173)

    pdf.set_y(35)
    pdf.set_font("helvetica", "B", 30)
    pdf.set_text_color(102, 126, 234)
    pdf.cell(0, 15, "SERTIFIKAT KELULUSAN", ln=True, align="C")

    pdf.ln(8)
    pdf.set_font("helvetica", "", 14)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 10, "Diberikan kepada:", ln=True, align="C")

    pdf.ln(4)
    pdf.set_font("helvetica", "B", 26)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 15, name, ln=True, align="C")

    pdf.ln(2)
    pdf.set_font("helvetica", "", 13)
    pdf.set_text_color(60, 60, 60)
    pdf.cell(0, 8, f"(ID Siswa: {sid})", ln=True, align="C")

    pdf.ln(10)
    pdf.set_font("helvetica", "", 14)
    pdf.multi_cell(
        0, 8,
        f"Telah berhasil menyelesaikan modul \"{module}\"\n"
        f"dengan nilai {score}/100",
        align="C",
        new_x=XPos.LMARGIN, new_y=YPos.NEXT,
    )

    pdf.ln(15)
    pdf.set_font("helvetica", "I", 11)
    pdf.cell(0, 8, f"Diterbitkan pada {datetime.now().strftime('%d %B %Y')}", ln=True, align="C")

    pdf.ln(15)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "Advanced Mini LMS Koding Anak", ln=True, align="C")

    return bytes(pdf.output())
